/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CtrlPasseador;
import java.awt.Font;
import java.awt.Image;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import model.Animal;
import model.Cliente;
import model.Passeador;

/**
 *
 * @author MrMojoBr
 */
public class FrameBuscaPasseador extends javax.swing.JFrame {
    
    DefaultTableModel modeloPro = new DefaultTableModel(){

        @Override
        public boolean isCellEditable(int i, int i1) {
            return false; //To change body of generated methods, choose Tools | Templates.
        }
    };
    
    List<Passeador> passeadores;
    CtrlPasseador ctrlPasseador = new CtrlPasseador();
    Cliente cliente;
    int idSelectedPasseio;
    
    ImageIcon iconErroTemp = new ImageIcon(getClass().getResource("icon/error.png"));
    ImageIcon iconErro = new ImageIcon(iconErroTemp.getImage().getScaledInstance(35, 35, Image.SCALE_SMOOTH));
    
    ImageIcon iconCheckTemp = new ImageIcon(getClass().getResource("icon/check.png"));
    ImageIcon iconCheck = new ImageIcon(iconCheckTemp.getImage().getScaledInstance(35, 35, Image.SCALE_SMOOTH));
    
    public void formataTable(){
        passeadores = ctrlPasseador.buscaProfissionais();
        
        modeloPro.setColumnIdentifiers(new String[] {
            "Nome","Preço/Hora","Avaliação"});
        modeloPro.setRowCount(0);
        if(!passeadores.isEmpty()){
            for(Passeador p: passeadores){
                modeloPro.addRow(new Object[]{
                    p.getNome(),
                    p.getValorHora(),
                    p.getAvaliacao()
                });
            }
        }
        
        jTableBuscaPasseador.setModel(modeloPro);
    }

    /**
     * Creates new form FrameBuscaPasseador
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public FrameBuscaPasseador() {
        initComponents();
        formataTable();
        
        URL iconURL = getClass().getResource("icon/petIcon.png");

        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Tahoma", Font.PLAIN, 14)));
    }
    
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public FrameBuscaPasseador(Cliente cli) {
        initComponents();
        formataTable();
        cliente = cli;
        
        URL iconURL = getClass().getResource("icon/petIcon.png");

        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Tahoma", Font.PLAIN, 14)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBuscaPasseador = new javax.swing.JTable();
        jButtonSolicitaPasseio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PetWalk");
        setLocation(new java.awt.Point(500, 300));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Passeadores Disponiveis");

        jTableBuscaPasseador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Preco/Hora", "Avaliação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBuscaPasseador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBuscaPasseadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBuscaPasseador);

        jButtonSolicitaPasseio.setText("Solicitar Passeio");
        jButtonSolicitaPasseio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSolicitaPasseioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(81, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSolicitaPasseio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonSolicitaPasseio))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSolicitaPasseioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSolicitaPasseioMouseClicked
        // TODO add your handling code here:
        //solicita passeio
        
        idSelectedPasseio = jTableBuscaPasseador.getSelectedRow();
        if(idSelectedPasseio < 0){
            
            JOptionPane.showMessageDialog(this, "Por favor, selecione um passeador!", "Aviso!", JOptionPane.WIDTH, iconErro);
        }else{
            //System.out.println(idSelectedPasseio);
            int idPasseador = passeadores.get(idSelectedPasseio).getId_passeador();
            FrameCadastroPasseio cadPasseio = new FrameCadastroPasseio(cliente.getId_cliente(), idPasseador);
            cadPasseio.setVisible(true);
        }

    }//GEN-LAST:event_jButtonSolicitaPasseioMouseClicked

    private void jTableBuscaPasseadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBuscaPasseadorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableBuscaPasseadorMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSolicitaPasseio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBuscaPasseador;
    // End of variables declaration//GEN-END:variables
}
