/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CtrlCliente;
import controller.CtrlPasseador;
import controller.CtrlPasseio;
import java.awt.Font;
import java.awt.Image;
import java.net.URL;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import model.Animal;
import model.Cliente;
import model.Passeador;
import model.Passeio;

/**
 *
 * @author MrMojoBr
 */
public class FrameCadastroPasseio extends javax.swing.JFrame {


    CtrlCliente ctrlCliente = new CtrlCliente();
    CtrlPasseador ctrlPasseador = new CtrlPasseador();
    Cliente cliente;
    Passeador passeador;
    
    
    List<Animal> pets;
    
    ImageIcon iconErroTemp = new ImageIcon(getClass().getResource("icon/error.png"));
    ImageIcon iconErro = new ImageIcon(iconErroTemp.getImage().getScaledInstance(35, 35, Image.SCALE_SMOOTH));
    
    ImageIcon iconCheckTemp = new ImageIcon(getClass().getResource("icon/check.png"));
    ImageIcon iconCheck = new ImageIcon(iconCheckTemp.getImage().getScaledInstance(35, 35, Image.SCALE_SMOOTH));
    
    
    /**
     * Creates new form FrameCadastroPasseio
     */
    

    public void formataFrame(int idCliente, int idPasseador){
        cliente = ctrlCliente.pesquisaCliente(idCliente);
        passeador = ctrlPasseador.pesquisaPasseador(idPasseador);
        
        jTextFieldNomeWalkPro.setText(passeador.getNome());
        
        pets = ctrlCliente.pesquisaAnimais(cliente.getId_cliente());
        
        jComboBoxPetCadWalk.removeAllItems();
        if(!pets.isEmpty()){
            for(Animal p: pets){
                jComboBoxPetCadWalk.addItem(p.getNome());
            }
        }
        double vh = (passeador.getValorHora() / 60) * Double.parseDouble(jFormattedTextFieldCadWalkDuracao.getText());
        jTextFieldCadWalkPreco.setText("R$ "+ String.format("%.2f", vh));
        
    }
    
    public FrameCadastroPasseio() {
        initComponents();
        
        URL iconURL = getClass().getResource("icon/petIcon.png");

        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Tahoma", Font.PLAIN, 14)));
    }
    
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public FrameCadastroPasseio(int idCliente, int idPasseador) {
        initComponents();
        formataFrame(idCliente, idPasseador);
        
        URL iconURL = getClass().getResource("icon/petIcon.png");

        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Tahoma", Font.PLAIN, 14)));
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeWalkPro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxPetCadWalk = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldCadWalkDataHora = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldCadWalkDuracao = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCadWalkPreco = new javax.swing.JTextField();
        jButtonConfirmaCadWalk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PetWalk");
        setLocation(new java.awt.Point(500, 300));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Cadastro de Passeio");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nome Passeador:");

        jTextFieldNomeWalkPro.setEditable(false);
        jTextFieldNomeWalkPro.setText("Nome Passeador");
        jTextFieldNomeWalkPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeWalkProActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Pet:");

        jComboBoxPetCadWalk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Data e Hora:");

        try {
            jFormattedTextFieldCadWalkDataHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCadWalkDataHora.setText("00/00/0000 00:00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Duração (Mn): ");

        try {
            jFormattedTextFieldCadWalkDuracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCadWalkDuracao.setText("00");
        jFormattedTextFieldCadWalkDuracao.setToolTipText("Duração em minutos.");
        jFormattedTextFieldCadWalkDuracao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCadWalkDuracaoFocusLost(evt);
            }
        });
        jFormattedTextFieldCadWalkDuracao.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jFormattedTextFieldCadWalkDuracaoInputMethodTextChanged(evt);
            }
        });
        jFormattedTextFieldCadWalkDuracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCadWalkDuracaoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Preço:");

        jTextFieldCadWalkPreco.setEditable(false);
        jTextFieldCadWalkPreco.setText("R$00.00");

        jButtonConfirmaCadWalk.setText("Confirmar");
        jButtonConfirmaCadWalk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmaCadWalkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxPetCadWalk, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCadWalkDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCadWalkDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCadWalkPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomeWalkPro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jButtonConfirmaCadWalk)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomeWalkPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxPetCadWalk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldCadWalkDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextFieldCadWalkDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCadWalkPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButtonConfirmaCadWalk)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeWalkProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeWalkProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeWalkProActionPerformed

    private void jFormattedTextFieldCadWalkDuracaoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCadWalkDuracaoInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCadWalkDuracaoInputMethodTextChanged

    private void jFormattedTextFieldCadWalkDuracaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCadWalkDuracaoKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jFormattedTextFieldCadWalkDuracaoKeyTyped

    private void jFormattedTextFieldCadWalkDuracaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCadWalkDuracaoFocusLost
        // TODO add your handling code here:
        try{
            double vh = (passeador.getValorHora() / 60) * Double.parseDouble(jFormattedTextFieldCadWalkDuracao.getText());
            jTextFieldCadWalkPreco.setText("R$ "+ String.format("%.2f", vh));
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jFormattedTextFieldCadWalkDuracaoFocusLost

    private void jButtonConfirmaCadWalkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmaCadWalkMouseClicked
        // TODO add your handling code here:
        //cadastro de passeio
        CtrlPasseio ctrlPasseio = new CtrlPasseio();
        Animal animal = new Animal();
        Passeio passeio = new Passeio(cliente, animal, passeador);
        
        int idSelectedAnimal = jComboBoxPetCadWalk.getSelectedIndex();
        
        passeio.getAnimal().setId_animal(pets.get(idSelectedAnimal).getId_animal());
        
        String formataData = jFormattedTextFieldCadWalkDataHora.getText();
        
        passeio.setDuracaoPasseio(Integer.parseInt(jFormattedTextFieldCadWalkDuracao.getText()));
        String preco = jTextFieldCadWalkPreco.getText().replace("R", "");
        preco = preco.replace("$","");
        preco = preco.replace(",", ".");
        preco = preco.trim();
        passeio.setPrecoPasseio(Float.parseFloat(preco));
 
        try{
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
            LocalDateTime data = LocalDateTime.parse(formataData, formatter);
            
            passeio.setAgendamentoPasseio(data);
            
            if((passeio.getPrecoPasseio() > 0) && data.isAfter(LocalDateTime.now())){
                passeio.setStatus(true);
                if(ctrlPasseio.cadastraPasseio(passeio)){
                    JOptionPane.showMessageDialog(this, "Passeio agendado com sucesso!", "Sucesso!", JOptionPane.WIDTH, iconCheck);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Ocorreu um erro no agendamento!", "Aviso!", JOptionPane.WIDTH, iconErro);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Por favor insira os dados corretamente!", "Aviso!", JOptionPane.WIDTH, iconErro);
            }
            
        }catch(DateTimeParseException e){
            JOptionPane.showMessageDialog(this, "Data inválida!", "Aviso!", JOptionPane.WIDTH, iconErro);
        }  
        
        
    }//GEN-LAST:event_jButtonConfirmaCadWalkMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmaCadWalk;
    private javax.swing.JComboBox<String> jComboBoxPetCadWalk;
    private javax.swing.JFormattedTextField jFormattedTextFieldCadWalkDataHora;
    private javax.swing.JFormattedTextField jFormattedTextFieldCadWalkDuracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldCadWalkPreco;
    private javax.swing.JTextField jTextFieldNomeWalkPro;
    // End of variables declaration//GEN-END:variables
}
