/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CtrlCliente;
import controller.CtrlPasseador;
import java.awt.Font;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import model.Cliente;
import model.Passeador;
import util.Valida;

/**
 *
 * @author MrMojoBr
 */
public class FrameCadastro extends javax.swing.JFrame {

    /**
     * Creates new form FrameCadastro
     */
    public FrameCadastro() {
        initComponents();
        
        URL iconURL = getClass().getResource("icon/petIcon.png");

        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Tahoma", Font.PLAIN, 14)));
    }
    
    public void trocaTabbedPane(int ind){
        try{
            jTabbedPaneCad.setSelectedIndex(ind);
        }catch(Exception e){
            
        }
        
    }
    
    CtrlCliente ctrlCliente = new CtrlCliente();
    CtrlPasseador ctrlPasseador = new CtrlPasseador();
    
    ImageIcon iconErroTemp = new ImageIcon(getClass().getResource("icon/error.png"));
    ImageIcon iconErro = new ImageIcon(iconErroTemp.getImage().getScaledInstance(35, 35, Image.SCALE_SMOOTH));
    
    ImageIcon iconCheckTemp = new ImageIcon(getClass().getResource("icon/check.png"));
    ImageIcon iconCheck = new ImageIcon(iconCheckTemp.getImage().getScaledInstance(35, 35, Image.SCALE_SMOOTH));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCad = new javax.swing.JLabel();
        jTabbedPaneCad = new javax.swing.JTabbedPane();
        jPanelCadCliente = new javax.swing.JPanel();
        jLabelCadClienteNome = new javax.swing.JLabel();
        jLabelCadClienteCPF = new javax.swing.JLabel();
        jLabelClienteCelular = new javax.swing.JLabel();
        jLabelCadClienteEndereco = new javax.swing.JLabel();
        jLabelCadClienteEmail = new javax.swing.JLabel();
        jLabelCadClienteSenha = new javax.swing.JLabel();
        jButtonCadCliente = new javax.swing.JButton();
        jTextFieldCadClienteEndereco = new javax.swing.JTextField();
        jTextFieldCadClienteEmail = new javax.swing.JTextField();
        jTextFieldCadClienteNome = new javax.swing.JTextField();
        jLabelCadClienteSexo = new javax.swing.JLabel();
        jComboBoxCadClienteSexo = new javax.swing.JComboBox<>();
        jPasswordFieldCadClienteSenha = new javax.swing.JPasswordField();
        jTextFieldCadClienteCPF = new javax.swing.JFormattedTextField();
        jTextFieldCadClienteCelular = new javax.swing.JFormattedTextField();
        jPanelCadProfissional = new javax.swing.JPanel();
        jLabelCadProNome = new javax.swing.JLabel();
        jLabelCadProSexo = new javax.swing.JLabel();
        jLabelCadProCPF = new javax.swing.JLabel();
        jLabelCadProValor = new javax.swing.JLabel();
        jLabelCadProEndereco = new javax.swing.JLabel();
        jLabelCadProCelular = new javax.swing.JLabel();
        jLabelCadProEmail = new javax.swing.JLabel();
        jLabelCadProSenha = new javax.swing.JLabel();
        jLabelCadProDescricao = new javax.swing.JLabel();
        jButtonCadPro = new javax.swing.JButton();
        jTextFieldCadProNome = new javax.swing.JTextField();
        jTextFieldCadProEndereco = new javax.swing.JTextField();
        jTextFieldCadProEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCadProDescricao = new javax.swing.JTextArea();
        jComboBoxCadProSexo = new javax.swing.JComboBox<>();
        jPasswordFieldCadProSenha = new javax.swing.JPasswordField();
        jTextFieldCadProCPF = new javax.swing.JFormattedTextField();
        jTextFieldCadProCelular = new javax.swing.JFormattedTextField();
        jTextFieldCadProCusto = new javax.swing.JFormattedTextField();
        jButtonCadLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetWalk");
        setLocation(new java.awt.Point(500, 300));
        setResizable(false);

        jLabelCad.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelCad.setText("Cadastro");

        jLabelCadClienteNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadClienteNome.setText("Nome:");

        jLabelCadClienteCPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadClienteCPF.setText("CPF:");

        jLabelClienteCelular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelClienteCelular.setText("Celular:");

        jLabelCadClienteEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadClienteEndereco.setText("Endereço:");

        jLabelCadClienteEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadClienteEmail.setText("E-Mail:");

        jLabelCadClienteSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadClienteSenha.setText("Senha:");

        jButtonCadCliente.setText("Cadastrar");
        jButtonCadCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadClienteMouseClicked(evt);
            }
        });
        jButtonCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadClienteActionPerformed(evt);
            }
        });

        jTextFieldCadClienteEndereco.setText("Bairro, Rua, Número - CEP");

        jTextFieldCadClienteEmail.setText("E-Mail");

        jTextFieldCadClienteNome.setText("Nome Completo");

        jLabelCadClienteSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadClienteSexo.setText("Sexo:");

        jComboBoxCadClienteSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino", "N/D" }));

        jPasswordFieldCadClienteSenha.setText("jPasswordField1");

        try {
            jTextFieldCadClienteCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCadClienteCPF.setText("000.000.000-00");

        try {
            jTextFieldCadClienteCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCadClienteCelular.setText("00000-0000");

        javax.swing.GroupLayout jPanelCadClienteLayout = new javax.swing.GroupLayout(jPanelCadCliente);
        jPanelCadCliente.setLayout(jPanelCadClienteLayout);
        jPanelCadClienteLayout.setHorizontalGroup(
            jPanelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadClienteLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCadClienteEndereco)
                    .addComponent(jLabelCadClienteEmail)
                    .addComponent(jLabelCadClienteNome)
                    .addComponent(jLabelCadClienteCPF)
                    .addComponent(jLabelCadClienteSexo)
                    .addComponent(jLabelClienteCelular)
                    .addComponent(jLabelCadClienteSenha))
                .addGap(41, 41, 41)
                .addGroup(jPanelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCadClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCadClienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCadClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCadClienteEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCadClienteSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCadClienteCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldCadClienteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jButtonCadCliente)
                .addGap(81, 81, 81))
        );
        jPanelCadClienteLayout.setVerticalGroup(
            jPanelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadClienteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadClienteNome)
                    .addComponent(jTextFieldCadClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadClienteCPF)
                    .addComponent(jTextFieldCadClienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadClienteEmail)
                    .addComponent(jTextFieldCadClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadClienteEndereco)
                    .addComponent(jTextFieldCadClienteEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadClienteSexo)
                    .addComponent(jComboBoxCadClienteSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteCelular)
                    .addComponent(jTextFieldCadClienteCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadClienteSenha)
                    .addComponent(jPasswordFieldCadClienteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPaneCad.addTab("Cliente", jPanelCadCliente);

        jLabelCadProNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadProNome.setText("Nome:");

        jLabelCadProSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadProSexo.setText("Sexo:");

        jLabelCadProCPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadProCPF.setText("CPF:");

        jLabelCadProValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadProValor.setText("Valor/Hora:");

        jLabelCadProEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadProEndereco.setText("Endereço:");

        jLabelCadProCelular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadProCelular.setText("Celular:");

        jLabelCadProEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadProEmail.setText("E-Mail:");

        jLabelCadProSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadProSenha.setText("Senha:");

        jLabelCadProDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadProDescricao.setText("Descrição:");

        jButtonCadPro.setText("Cadastrar");
        jButtonCadPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadProMouseClicked(evt);
            }
        });

        jTextFieldCadProNome.setText("Nome Completo");

        jTextFieldCadProEndereco.setText("Bairro, Rua, Número - CEP");

        jTextFieldCadProEmail.setText("E-Mail");

        jTextAreaCadProDescricao.setColumns(20);
        jTextAreaCadProDescricao.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextAreaCadProDescricao.setRows(5);
        jTextAreaCadProDescricao.setText("Insira uma descrição sobre você.");
        jScrollPane1.setViewportView(jTextAreaCadProDescricao);

        jComboBoxCadProSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino", "N/D" }));
        jComboBoxCadProSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCadProSexoActionPerformed(evt);
            }
        });

        jPasswordFieldCadProSenha.setText("jPasswordField1");

        try {
            jTextFieldCadProCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCadProCPF.setText("000.000.000-00");

        try {
            jTextFieldCadProCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCadProCelular.setText("00000-0000");

        try {
            jTextFieldCadProCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCadProCusto.setText("00.00");

        javax.swing.GroupLayout jPanelCadProfissionalLayout = new javax.swing.GroupLayout(jPanelCadProfissional);
        jPanelCadProfissional.setLayout(jPanelCadProfissionalLayout);
        jPanelCadProfissionalLayout.setHorizontalGroup(
            jPanelCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadProfissionalLayout.createSequentialGroup()
                .addGroup(jPanelCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadProfissionalLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCadProEmail)
                            .addComponent(jLabelCadProEndereco)
                            .addComponent(jLabelCadProDescricao)
                            .addComponent(jLabelCadProNome)
                            .addComponent(jLabelCadProSexo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCadProEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCadProEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCadProSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCadProNome, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelCadProfissionalLayout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addComponent(jLabelCadProCelular))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadProfissionalLayout.createSequentialGroup()
                                    .addGap(95, 95, 95)
                                    .addComponent(jLabelCadProSenha)))
                            .addGroup(jPanelCadProfissionalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelCadProCPF)
                                    .addComponent(jLabelCadProValor))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCadProCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCadProCusto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCadProCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordFieldCadProSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCadProfissionalLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButtonCadPro)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadProfissionalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanelCadProfissionalLayout.setVerticalGroup(
            jPanelCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadProfissionalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadProNome)
                    .addComponent(jLabelCadProCPF)
                    .addComponent(jTextFieldCadProNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCadProCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadProSexo)
                    .addComponent(jLabelCadProValor)
                    .addComponent(jComboBoxCadProSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCadProCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadProEndereco)
                    .addComponent(jLabelCadProCelular)
                    .addComponent(jTextFieldCadProEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCadProCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadProEmail)
                    .addComponent(jLabelCadProSenha)
                    .addComponent(jTextFieldCadProEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldCadProSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelCadProDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadPro)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPaneCad.addTab("Profissional", jPanelCadProfissional);

        jButtonCadLogin.setText("Login");
        jButtonCadLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jTabbedPaneCad, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabelCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadLogin)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCad)
                    .addComponent(jButtonCadLogin))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPaneCad, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCadProSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCadProSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCadProSexoActionPerformed

    private void jButtonCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadClienteActionPerformed

    private void jButtonCadClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadClienteMouseClicked
        // TODO add your handling code here:
        //Cadastro de cliente
        
        Cliente cliente = new Cliente();
        
        cliente.setNome(jTextFieldCadClienteNome.getText());
        cliente.setCpf(jTextFieldCadClienteCPF.getText());
        cliente.setEmail(jTextFieldCadClienteEmail.getText());
        cliente.setEndereco(jTextFieldCadClienteEndereco.getText());
        cliente.setSexo(jComboBoxCadClienteSexo.getSelectedItem().toString());
        cliente.setCelular(jTextFieldCadClienteCelular.getText());
        cliente.setPsw(String.valueOf(jPasswordFieldCadClienteSenha.getPassword()));
        
        Valida valida = new Valida();
        String erros = valida.validaCliente(cliente);
        if(!erros.equals("")){
             JOptionPane.showMessageDialog(this, erros, "Aviso!", JOptionPane.WIDTH, iconErro);
        }else{
            if(ctrlCliente.pesquisaEmail(cliente.getEmail())){
                if(ctrlCliente.cadastroCliente(cliente)){
                    JOptionPane.showMessageDialog(this, "Cadastro efetuado com sucesso!", "Cadastrado!",JOptionPane.WIDTH, iconCheck);
                    FrameLogin fLogin = new FrameLogin();
                    
                    fLogin.trocaTabbedPane(jTabbedPaneCad.getSelectedIndex());
                    fLogin.setVisible(true);
                    
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar!", "Aviso!", JOptionPane.WIDTH, iconErro);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Email já cadastrado!", "Aviso!", JOptionPane.WIDTH, iconErro);
            }
        }
        
    }//GEN-LAST:event_jButtonCadClienteMouseClicked

    private void jButtonCadLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadLoginMouseClicked
        // TODO add your handling code here:
      //retornar ao login
        
        
        FrameLogin fLogin = new FrameLogin();
                    
        fLogin.trocaTabbedPane(jTabbedPaneCad.getSelectedIndex());
        fLogin.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_jButtonCadLoginMouseClicked

    private void jButtonCadProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadProMouseClicked
        // TODO add your handling code here:
        //cadastro de passeador
        Passeador passeador = new Passeador();
        
        
        passeador.setNome(jTextFieldCadProNome.getText());
        passeador.setCpf(jTextFieldCadProCPF.getText());
        passeador.setSexo(jComboBoxCadProSexo.getSelectedItem().toString());
        passeador.setValorHora(Double.parseDouble(jTextFieldCadProCusto.getText()));
        passeador.setEndereco(jTextFieldCadProEndereco.getText());
        passeador.setCelular(jTextFieldCadProCelular.getText());
        passeador.setEmail(jTextFieldCadProEmail.getText());
        passeador.setPsw(String.valueOf(jPasswordFieldCadProSenha.getPassword()));
        passeador.setDescricao(jTextAreaCadProDescricao.getText());
        
        
        Valida valida = new Valida();
        String erros = valida.validaPasseador(passeador);
        if(!erros.equals("")){
             JOptionPane.showMessageDialog(this, erros, "Aviso!", JOptionPane.WIDTH, iconErro);
        }else{
            if(ctrlPasseador.pesquisaEmail(passeador.getEmail())){
                if(ctrlPasseador.cadastroPasseador(passeador)){
                    JOptionPane.showMessageDialog(this, "Cadastro efetuado com sucesso!", "Cadastrado!", JOptionPane.WIDTH, iconCheck);
                    
                    FrameLogin fLogin = new FrameLogin();
                    
                    fLogin.trocaTabbedPane(jTabbedPaneCad.getSelectedIndex());
                    fLogin.setVisible(true);
                    
                    this.dispose();
                
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar!", "Aviso!", JOptionPane.WIDTH, iconErro);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Email já cadastrado!", "Aviso!", JOptionPane.WIDTH, iconErro);
            }
        }
    }//GEN-LAST:event_jButtonCadProMouseClicked

    /**
     * @param args the command line arguments
     */
     
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadCliente;
    private javax.swing.JButton jButtonCadLogin;
    private javax.swing.JButton jButtonCadPro;
    private javax.swing.JComboBox<String> jComboBoxCadClienteSexo;
    private javax.swing.JComboBox<String> jComboBoxCadProSexo;
    private javax.swing.JLabel jLabelCad;
    private javax.swing.JLabel jLabelCadClienteCPF;
    private javax.swing.JLabel jLabelCadClienteEmail;
    private javax.swing.JLabel jLabelCadClienteEndereco;
    private javax.swing.JLabel jLabelCadClienteNome;
    private javax.swing.JLabel jLabelCadClienteSenha;
    private javax.swing.JLabel jLabelCadClienteSexo;
    private javax.swing.JLabel jLabelCadProCPF;
    private javax.swing.JLabel jLabelCadProCelular;
    private javax.swing.JLabel jLabelCadProDescricao;
    private javax.swing.JLabel jLabelCadProEmail;
    private javax.swing.JLabel jLabelCadProEndereco;
    private javax.swing.JLabel jLabelCadProNome;
    private javax.swing.JLabel jLabelCadProSenha;
    private javax.swing.JLabel jLabelCadProSexo;
    private javax.swing.JLabel jLabelCadProValor;
    private javax.swing.JLabel jLabelClienteCelular;
    private javax.swing.JPanel jPanelCadCliente;
    private javax.swing.JPanel jPanelCadProfissional;
    private javax.swing.JPasswordField jPasswordFieldCadClienteSenha;
    private javax.swing.JPasswordField jPasswordFieldCadProSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneCad;
    private javax.swing.JTextArea jTextAreaCadProDescricao;
    private javax.swing.JFormattedTextField jTextFieldCadClienteCPF;
    private javax.swing.JFormattedTextField jTextFieldCadClienteCelular;
    private javax.swing.JTextField jTextFieldCadClienteEmail;
    private javax.swing.JTextField jTextFieldCadClienteEndereco;
    private javax.swing.JTextField jTextFieldCadClienteNome;
    private javax.swing.JFormattedTextField jTextFieldCadProCPF;
    private javax.swing.JFormattedTextField jTextFieldCadProCelular;
    private javax.swing.JFormattedTextField jTextFieldCadProCusto;
    private javax.swing.JTextField jTextFieldCadProEmail;
    private javax.swing.JTextField jTextFieldCadProEndereco;
    private javax.swing.JTextField jTextFieldCadProNome;
    // End of variables declaration//GEN-END:variables
}
